// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xsibgcxjnmlhcthuymqu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhzaWJnY3hqbm1saGN0aHV5bXF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIxMzUxMzEsImV4cCI6MjA1NzcxMTEzMX0.aTHTHsLoPnaFfS-LiLrD9dOmP1cKKiCEk8VbojGnACk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);